# This workflow will do a clean install of node dependencies, build the source
# code and run lints and tests.

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - releases/**

jobs:
  lint:
    name: CI
    strategy:
      matrix:
        node:
          - "14"
          - "16"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Setup Node.js
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup pnpm
        run: |-
          corepack enable
          pnpm --version

      - name: Set pnpm store-dir
        run: pnpm config set store-dir ~/.pnpm-store

      - name: Cache pnpm modules
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # renovate: tag=v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-current-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-current

      - name: Install packages
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Run linter
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test:coverage

      - name: Export coverage report
        run: pnpm run test:coverage-lcov

      - name: Upload report to CodeCov
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # renovate: tag=v2
        with:
          files: ./coverage/lcov.info
