name: Extended CI
on: workflow_dispatch

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Extended Test / ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Checkout main
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
        run: git remote set-branches --add origin main && git fetch origin main --depth 1

      - name: Setup Node.js
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          node-version: "16"

      - name: Setup pnpm
        run: |-
          corepack enable
          pnpm --version

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Cache pnpm modules
        uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d # tag=v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.OS }}-pnpm-current-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-current

      - name: Install packages
        run: pnpm install

      - name: Build
        run: pnpm exec nx run-many --target=build

      - name: Run extended tests
        run: pnpm exec nx run-many --target=test:extended
